### ISSUE TITLE
Error: Activity class {com.blereactnativesample/com.blereactnativesample.MainActivity} does not exist.

### ISSUE THREAD

**Issue by acmeneel** [friyiajr/BLEReactNativeSample#2]
After cloning project and installing node modules when I tried to run on android it shows build successful but get following error:
```
BUILD SUCCESSFUL in 21s
46 actionable tasks: 46 executed
info Connecting to the development server...
info Starting the app on "ZD2222B3T8"...
Starting: Intent { cmp=com.blereactnativesample/.MainActivity }
Error type 3
Error: Activity class {com.blereactnativesample/com.blereactnativesample.MainActivity} does not exist.
```

**Comment by friyiajr** [comment]
Normally this means something went wrong when installing. When this happens to me usually I just use the instructions here: https://stackoverflow.com/a/24241687. I would start with `adb uninstall <package>` though
